import streamlit
streamlit.title("My fist app /n")
streamlit.header(" I want to become snowflake SME")
streamlit.text("learning from Snowflake learn")
streamlit.text("lot of good courses")
streamlit.text("recommend to everyone")
streamlit.header('Breakfast Menu')
streamlit.text('Omega 3 & Blueberry Oatmeal')
streamlit.text('Kale, Spinach & Rocket Smoothie')
streamlit.text('Hard-Boiled Free-Range Egg')
